name: morphotester
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - pillow
  - pyqt=5
  - traits
  - traitsui
  - mayavi
  - vtk
  - pip
  - pip:
    - pyinstaller
